### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hasufell** [jerbob92/TrelloToJira#2]
```
FATA[0000] Could not get JIRA client: No user is authenticated yet
```

Everything is supplied, username and password are correct.

**Comment by jerbob92** [comment]
@hasufell it might be that they changed something on auth level, or your account requires 2fa? Sadly not really have time to test.

**Comment by jerbob92** [comment]
Maybe try this https://confluence.atlassian.com/cloud/api-tokens-938839638.html
Use email as user name and api token as password?
